name: publish
on: [push]
jobs:
  publish-mtu-searcher-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the mtu-searcher Docker image
        run: |
            docker build ./lab2 --tag ghcr.io/ksenia-c/mtu-searcher:latest
            docker run ghcr.io/ksenia-c/mtu-searcher:latest
            docker push ghcr.io/ksenia-c/mtu-searcher:latest
